[package]
name = "linear_regression"
version = "0.1.0"
authors = ["Julien Refour <julien@urbanlogiq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
